# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 02:37
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20148)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('address', models.CharField(max_length=2048)),
                ('facebook', models.URLField(blank=True, max_length=1024, null=True)),
                ('twitter', models.URLField(blank=True, max_length=1024, null=True)),
                ('email', models.CharField(blank=True, max_length=1024, null=True)),
                ('website', models.CharField(blank=True, max_length=2048, null=True)),
                ('logo', models.ImageField(upload_to='media/')),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('theme', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('publish', models.BooleanField(default=True)),
                ('exhibitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booth', to='schedule.Exhibitor')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point', to='schedule.Floor')),
            ],
        ),
        migrations.AddField(
            model_name='installation',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booth', to='schedule.Point'),
        ),
        migrations.AddField(
            model_name='event',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='schedule.Installation'),
        ),
        migrations.AddField(
            model_name='event',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='schedule.Point'),
        ),
    ]
