# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='name',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
