# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 03:06
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_installation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1024)),
                ('last_name', models.CharField(max_length=1024)),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField()),
                ('website', models.URLField(blank=True, max_length=1024, null=True)),
                ('facebook', models.URLField(blank=True, max_length=1024, null=True)),
                ('twitter', models.URLField(blank=True, max_length=1024, null=True)),
                ('email', models.CharField(blank=True, max_length=1024, null=True)),
                ('photo', models.ImageField(upload_to='media/speakers/')),
            ],
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='logo',
            field=models.ImageField(upload_to='media/exhibitors/'),
        ),
    ]
