# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20170810_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
