# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20170810_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='', upload_to='media/evenets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floor',
            name='plan',
            field=models.ImageField(blank=True, null=True, upload_to='medida/plans/'),
        ),
        migrations.AddField(
            model_name='installation',
            name='photo',
            field=models.ImageField(default='', upload_to='media/installations/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/points/'),
        ),
    ]
